export ZDOTDIR="$HOME/.config/zsh/"
export PATH="$HOME/.local/bin:$PATH"
export EDITOR="emacsclient -c -a ''"
export VISUAL="$EDITOR"
export PROMPT="[%n@%m:%~]$ "
export BROWSER="firefox"
export SSH_AUTH_SOCK="$HOME/.1password/agent.sock"
export GNUPGHOME="$XDG_CONFIG_HOME/gnupg/"
