[General]
filedialog-path=@Variant(\0\0\0\x11\0\0\0]file:///home/kam/Downloads/Torrents/Invincible.2021.S04E02.1080p.WEB.h264-ETHEL[EZTVx.to].mkv)
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\x6\0\0\0\x6\0\0\x4\xfb\0\0\x5\x99\0\0\0\x6\0\0\0\x6\0\0\x4\xfb\0\0\x5\x99\0\0\0\0\0\0\0\0\n\0\0\0\0\x6\0\0\0\x6\0\0\x4\xfb\0\0\x5\x99)

[FullScreen]
pos=@Point(0 0)
screen=@Rect(0 0 0 0)
wide=false

[MainWindow]
adv-controls=0
bgSize=@Size(600 0)
pl-dock-status=true
playlist-visible=false
playlistSize=@Size(-1 -1)
status-bar-visible=false

[RecentsMRL]
list=file:///home/kam/Downloads/Torrents/Inglourious%20Basterds%202009%201080p%20BluRay%20HEVC%20x265%205.1%20BONE.mkv, file:///home/kam/Downloads/Torrents/Invincible.2021.S04E02.1080p.WEB.h264-ETHEL[EZTVx.to].mkv, file:///home/kam/Downloads/Torrents/Invincible%20-%20S04E01%20-%20MAKING%20THE%20WORLD%20A%20BETTER%20PLACE.mkv, file:///home/kam/Downloads/Torrents/www.UIndex.org%20%20%20%20-%20%20%20%20Invincible.2021.S04E01.1080p.WEB.h264-ETHEL/Invincible.2021.S04E01.1080p.WEB.h264-ETHEL.mkv
times=0, 0, 0, 0
