[General]
filedialog-path=@Variant(\0\0\0\x11\0\0\0\t/home/kam)
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\x6\0\0\0\x6\0\0\x4\xfb\0\0\x5\x99\0\0\0\x6\0\0\0\x6\0\0\x4\xfb\0\0\x5\x99\0\0\0\0\0\0\0\0\n\0\0\0\0\x6\0\0\0\x6\0\0\x4\xfb\0\0\x5\x99)

[FullScreen]
pos=@Point(0 0)
screen=@Rect(0 0 0 0)
wide=false

[MainWindow]
adv-controls=0
bgSize=@Size(1270 1358)
pl-dock-status=true
playlist-visible=false
playlistSize=@Size(-1 -1)
status-bar-visible=false

[RecentsMRL]
list=file:///home/kam/Pictures/Wallpapers/tianshu-liu-aqZ3UAjs_M4-unsplash.jpg, file:///home/kam/Pictures/Wallpapers/timo-volz-DGsqL2j028E-unsplash.jpg, file:///home/kam/Pictures/Wallpapers/yu-kato-824OwkP7sgk-unsplash.jpg, file:///home/kam/Pictures/Wallpapers/zhaoli-jin-e4I2ktXz5cA-unsplash.jpg, file:///home/kam/Pictures/Wallpapers/shooting_star.png, file:///home/kam/Pictures/Wallpapers/morning_train.jpg, file:///home/kam/Pictures/Wallpapers/metropolis.jpg, file:///home/kam/Pictures/Wallpapers/hollywood_boulevard.jpg, file:///home/kam/Pictures/Wallpapers/alex-knight-DpPutJwgyW8-unsplash.jpg
times=0, 0, 0, 0, 0, 0, 0, 0, 0
